apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-api-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: simple-api
  template:
    metadata:
      labels:
        app: simple-api
    spec:
      containers:
        - name: simple-api
          image: simple-app-api:latest
          imagePullPolicy: Never # default pull from remote. Need set "Never"
          resources:
            limits:
              memory: "600Mi"
              cpu: "1"
---
apiVersion: v1
kind: Service
metadata:
  name: simple-api-clusterip-srv
spec:
  selector:
    app: simple-api
  type: NodePort
  ports:
    - name: simple-api
      protocol: TCP
      port: 3333
      targetPort: 3333
