name: Deploy web app

on:
  push:
    branches:
      - master
    paths:
      - "ng-todo-app/**"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: "Docker starting build image ..."
        run: cd ng-todo-app && docker build -t $DOCKER_IMAGE:$DOCKER_TAG .
      - name: "Docker starting to the docker hub ..."
        run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
      - name: "Docker starting push image to the docker hub ..."
        run: docker push $DOCKER_IMAGE:$DOCKER_TAG
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
          DOCKER_IMAGE: ngtrdai197/simple-ng-todo-app
          DOCKER_TAG: latest
