name: Deploy API

on:
  push:
    branches:
      - master
    paths:
      - "api/**"
  pull_request:
    branches:
      - master
    paths:
      - "api/**"
jobs:
  test-api:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: ['12']
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies
        run: cd api && npm install
      - name: Run testing by Jest
        run: cd api && npm run test

  build-and-push-docker:
    runs-on: ubuntu-latest
    needs: test-api
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: api
          push: true
          tags: ngtrdai197/simple-app-api:latest
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
