name: Deploy web app

on:
  push:
    branches:
      - master
    paths:
      - "ng-todo-app/**"
jobs:
  build-and-push-docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: ./ng-todo-app
          push: true
          tags: ngtrdai197/simple-ng-todo-app:latest

  deploy-web-app:
    runs-on: ubuntu-latest
    needs: build-and-push-docker
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Executing remote ssh commands using ssh key
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER_NAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: sh ./simple-app.sh

