name: Deploy API

on:
  push:
    branches:
      - master
    # paths:
    #   - "api/**"
  pull_request:
    branches:
      - master
    # paths:
    #   - "api/**"
jobs:
  test-api:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: ["12"]
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies
        run: cd api && npm install
      - name: Run testing by Jest
        run: cd api && npm run test

  build-and-push-docker:
    runs-on: ubuntu-latest
    needs: test-api
    steps:
      - uses: actions/checkout@v2
      - name: "Docker starting build image ..."
        run: cd api && docker build -t $DOCKER_IMAGE:$DOCKER_TAG .
      - name: "Docker starting login to the docker hub ..."
        run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
      - name: "Docker starting push image to the docker hub ..."
        run: docker push $DOCKER_IMAGE:$DOCKER_TAG
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
          DOCKER_IMAGE: ngtrdai197/simple-app-api
          DOCKER_TAG: latest
